### ISSUE TITLE
unable to get to prompt 

### ISSUE THREAD

**Issue by Sheshiyer** [theshanergy/whatbot#1]
### npm error
![image](https://user-images.githubusercontent.com/7611727/102013481-74cd9f00-3d76-11eb-8329-d1350f416c00.png)

**Comment by theshanergy** [comment]
Fixed with commit be1814f23d57c4ddedc4bac2d471e9621e71013e

**Comment by Sheshiyer** [comment]
thank you so much, this error has been resolved and now i can proceed to the stage of contact seletion and getting the message from the contact on the terminal. Althought getting a 401 error. 

![image](https://user-images.githubusercontent.com/7611727/102092307-efb1bb00-3e45-11eb-9257-39ff7e0fb1bf.png)

appreciate the support.

**Comment by theshanergy** [comment]
401 is an authorization error which in this case is being returned by the GPT-3 request. Have you specified your 'OPENAI_SECRET_KEY' in the .env file?
